export const countriesByLetter: { [key: string]: string[] } = {
    A: [
        "Afghanistan",
        "Albania",
        "Algerie",
        "Andorra",
        "Angola",
        "Antigua og Barbuda",
        "Argentina",
        "Armenia",
        "Aserbajdsjan",
        "Australia",
    ],
    B: [
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus (Hviterussland)",
        "Belgia",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia-Hercegovina",
        "Botswana",
        "Brasil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
    ],
    C: ["Canada", "Chile", "Colombia", "Cookøyene", "Costa Rica", "Cuba"],
    D: [
        "Danmark",
        "De forente arabiske emirater",
        "Den dominikanske republikk",
        "Den sentralafrikanske republikk",
        "Djibouti",
        "Dominica",
    ],
    E: [
        "Ecuador",
        "Egypt",
        "Ekvatorial-Guinea",
        "El Salvador",
        "Elfenbenskysten",
        "Eritrea",
        "Estland",
        "Eswatini",
        "Etiopia",
    ],
    F: ["Fiji", "Filippinene", "Finland", "Frankrike"],
    G: [
        "Gabon",
        "Gambia",
        "Georgia",
        "Ghana",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
    ],
    H: ["Haiti", "Hellas", "Honduras"],
    I: [
        "India",
        "Indonesia",
        "Irak",
        "Iran",
        "Irland",
        "Island",
        "Israel",
        "Italia",
    ],
    J: ["Jamaica", "Japan", "Jemen", "Jordan"],
    K: [
        "Kambodsja",
        "Kamerun",
        "Kapp Verde",
        "Kasakhstan",
        "Kenya",
        "Kina",
        "Kirgisistan",
        "Kiribati",
        "Komorene",
        "Kongo, Den demokratiske republikken",
        "Kongo, Republikken",
        "Kosovo",
        "Kroatia",
        "Kuwait",
        "Kypros",
    ],
    L: [
        "Laos",
        "Latvia",
        "Lesotho",
        "Libanon",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Litauen",
        "Luxembourg",
    ],
    M: [
        "Madagaskar",
        "Malawi",
        "Malaysia",
        "Maldivene",
        "Mali",
        "Malta",
        "Marokko",
        "Marshalløyene",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Mikronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Mosambik",
        "Myanmar (Burma)",
    ],
    N: [
        "Namibia",
        "Nauru",
        "Nederland",
        "Nepal",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Nord-Korea",
        "Nord-Makedonia",
        "Norge",
    ],
    O: ["Oman"],

    P: [
        "Pakistan",
        "Palau",
        "Palestina",
        "Panama",
        "Papua Ny-Guinea",
        "Paraguay",
        "Peru",
        "Polen",
        "Portugal",
    ],
    Q: ["Qatar"],
    R: ["Romania", "Russland", "Rwanda"],
    S: [
        "Saint Kitts og Nevis",
        "Saint Lucia",
        "Saint Vincent og Grenadinene",
        "Salomonøyene",
        "Samoa",
        "San Marino",
        "São Tomé og Príncipe",
        "Saudi-Arabia",
        "Senegal",
        "Serbia",
        "Seychellene",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Somalia",
        "Spania",
        "Sri Lanka",
        "Storbritannia",
        "Sudan",
        "Surinam",
        "Sveits",
        "Sverige",
        "Syria",
        "Sør-Afrika",
        "Sør-Korea",
        "Sør-Sudan",
    ],
    T: [
        "Tadsjikistan",
        "Taiwan",
        "Tanzania",
        "Thailand",
        "Togo",
        "Tonga",
        "Trinidad og Tobago",
        "Tsjad",
        "Tsjekkia",
        "Tunisia",
        "Turkmenistan",
        "Tuvalu",
        "Tyrkia",
        "Tyskland",
    ],
    U: ["Uganda", "Ukraina", "Ungarn", "Uruguay", "USA", "Usbekistan"],
    V: ["Vanuatu", "Vatikanstaten", "Venezuela", "Vest-Sahara", "Vietnam"],
    Z: ["Zambia", "Zimbabwe"],
    Ø: ["Øst-Timor", "Østerrike"],
};
